# Generated by Django 3.0.8 on 2020-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=100)),
                ('in_time', models.TimeField(auto_now=True)),
                ('out_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
