# Generated by Django 3.0.8 on 2020-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='out_time',
            field=models.TimeField(),
        ),
    ]
