# Generated by Django 3.0.8 on 2020-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200704_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='overtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
